daysUntilStale: 60
daysUntilClose: 7
onlyLabels: []
exemptLabels:
  - se
  - support
exemptProjects: false
exemptMilestones: false
exemptAssignees: false
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  Closing due to inactivity
limitPerRun: 30
