language: python
python:
  - "3.6"
install:
  - pip install -rrequirements.txt -rtest-requirements.txt .
script:
  - pytest
  - coverage run zapier_fun/test_things.py
  - flake8
after_success:
  - codecov
